import { execSync } from 'child_process';

<<<<<<< HEAD
describe('# sgen-react-native integration test', () => {
=======
describe('# integration test', () => {
>>>>>>> 4fe72e3... generated by 
    beforeEach(() => {
        execSync('rm -rf testoutput');
    });

    it('## should print help options', () => {
<<<<<<< HEAD
        const output = execSync('./scripts/sgen-react-native.sh -h').toString();
        expect(output).toMatchSnapshot();
    });

    it('## should generate design', () => {
        const output = execSync(
            './scripts/sgen-react-native.sh -d src/test/fixture/design.js -o testoutput'
        ).toString();
        expect(output).toMatchSnapshot();
    });

    it('## should generate design and run react-native commands', () => {
        let output = execSync('./scripts/sgen-react-native.sh -d src/test/fixture/design.js -o testoutput').toString();
        expect(output).toMatchSnapshot();
        output = execSync('npm install', { cwd: 'testoutput' }).toString();
        output = execSync('npm run lint', { cwd: 'testoutput' }).toString();
    });
});

describe('# sgen-react-native-nav integration test', () => {
    beforeEach(() => {
        execSync('rm -rf testoutput');
    });

    it('## should print help options', () => {
        const output = execSync('./scripts/sgen-react-native-nav.sh -h').toString();
        expect(output).toMatchSnapshot();
    });

    it('## should generate design', () => {
        const output = execSync(
            './scripts/sgen-react-native-nav.sh -d src/test/fixture/nav.json -o testoutput'
        ).toString();
=======
        let output = execSync('npm run build').toString();
        output = execSync('sgen -g `pwd`/dist/react-native.min.js -h').toString();
>>>>>>> 4fe72e3... generated by 
        expect(output).toMatchSnapshot();
    });

    it('## should generate design and run react-native commands', () => {
<<<<<<< HEAD
        let output = execSync(
            './scripts/sgen-react-native-nav.sh -d src/test/fixture/nav.json -o testoutput'
=======
        let output = execSync('npm run build').toString();
        output = execSync(
            'sgen -g `pwd`/dist/react-native.min.js -d src/test/fixture/design.json -o testoutput'
>>>>>>> 4fe72e3... generated by 
        ).toString();
        output = output.replace(/info: Loaded generator .*react-native.min.js.*/, '');
        expect(output).toMatchSnapshot();
        execSync('npm install', { cwd: 'testoutput', stdio: 'inherit' });
        execSync('npm run lint', { cwd: 'testoutput', stdio: 'inherit' });
        execSync('npm run build', { cwd: 'testoutput', stdio: 'inherit' });
    });
});
